//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <AWSCore/AWSCore.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:c61fefb4-31df-443b-be34-89c5fa30888d"
//#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:29222dbd-8d76-428a-bd37-5524bbfce438"
#define AMAZON_COGNITO_IDENTITY_POOL_ARN @"arn:aws:cognito-identity:us-east-1:190501226333:identitypool/us-east-1:29222dbd-8d76-428a-bd37-5524bbfce438"

// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 6ee5fbb8-4cab-4cd9-85a2-a54cd53fdf4e aws-my-sample-app-ios-objc-v0.6"

//DYNAMODB
#define DYNAMODB_USERS_TABLE_NAME @"Users"
#define DYNAMODB_JAMTRAKS_TABLE_NAME @"JamTracks"

//S3 (CD)
#define AMAZON_S3_BUCKET_NAME @"usersjamtracks"
//Oregon
#define AMAZON_S3_BUCKET_REGION



