//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <AWSCore/AWSCore.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:29222dbd-8d76-428a-bd37-5524bbfce438"
#define AMAZON_COGNITO_IDENTITY_POOL_ARN @"arn:aws:cognito-identity:us-east-1:190501226333:identitypool/us-east-1:29222dbd-8d76-428a-bd37-5524bbfce438"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"jamwith-contentdelivery-mobilehub-709331185"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 6ee5fbb8-4cab-4cd9-85a2-a54cd53fdf4e aws-my-sample-app-ios-objc-v0.6"
